---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: movienight-backend
  namespace: movienight
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore

  target:
    name: movienight-backend
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        JELLYFIN_BASE_URL: "{{ .jellyfinBaseUrl }}"
        JELLYFIN_WEB_URL: "{{ .jellyfinWebUrl }}"
        JELLYFIN_PLUGIN_TOKEN: "{{ .jellyfinPluginToken }}"
        JELLYFIN_API_KEY: "{{ .jellyfinApiKey }}"
        OAUTH2_GOOGLE_CLIENT_ID: "{{ .googleClientId }}"
        OAUTH2_GOOGLE_CLIENT_SECRET: "{{ .googleClientSecret }}"
        OAUTH2_YANDEX_CLIENT_ID: "{{ .yandexClientId }}"
        OAUTH2_YANDEX_CLIENT_SECRET: "{{ .yandexClientSecret }}"
        OAUTH2_VK_CLIENT_ID: "{{ .vkClientId }}"
        OAUTH2_VK_CLIENT_SECRET: "{{ .vkClientSecret }}"

  data:
    - secretKey: jellyfinBaseUrl
      remoteRef:
        key: /movienight/MOVIENIGHT_JELLYFIN_BASE_URL
    - secretKey: jellyfinWebUrl
      remoteRef:
        key: /movienight/MOVIENIGHT_JELLYFIN_WEB_URL
    - secretKey: jellyfinPluginToken
      remoteRef:
        key: /movienight/MOVIENIGHT_JELLYFIN_PLUGIN_TOKEN
    - secretKey: jellyfinApiKey
      remoteRef:
        key: /movienight/MOVIENIGHT_JELLYFIN_API_KEY
    - secretKey: googleClientId
      remoteRef:
        key: /movienight/MOVIENIGHT_OAUTH2_GOOGLE_CLIENT_ID
    - secretKey: googleClientSecret
      remoteRef:
        key: /movienight/MOVIENIGHT_OAUTH2_GOOGLE_CLIENT_SECRET
    - secretKey: yandexClientId
      remoteRef:
        key: /movienight/MOVIENIGHT_OAUTH2_YANDEX_CLIENT_ID
    - secretKey: yandexClientSecret
      remoteRef:
        key: /movienight/MOVIENIGHT_OAUTH2_YANDEX_CLIENT_SECRET
    - secretKey: vkClientId
      remoteRef:
        key: /movienight/MOVIENIGHT_OAUTH2_VK_CLIENT_ID
    - secretKey: vkClientSecret
      remoteRef:
        key: /movienight/MOVIENIGHT_OAUTH2_VK_CLIENT_SECRET

  refreshInterval: 1h
