---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://vault.itqdev.xyz
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-secret
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: infisical-secret
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        projectSlug: default-c-nay
        environmentSlug: prod
        secretsPath: /
