{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "movienight.fullname" . }}-backend
  labels:
    {{- include "movienight.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.backend.management.enabled }}
    - name: management
      port: {{ .Values.backend.management.port }}
      targetPort: management
      protocol: TCP
    {{- end }}
  selector:
    {{- include "movienight.componentSelectorLabels" (dict "root" . "component" "backend") | nindent 4 }}
{{- end }}
