apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-agent
    targetRevision: 0.11.0
    helm:
      releaseName: vmagent
      valuesObject:
        remoteWrite:
          - url: http://vmsingle-victoria-metrics-single.observability.svc:8428/api/v1/write
        config:
          scrape_interval: 10s
          scrape_configs:
            - job_name: 'movienight-backend'
              metrics_path: /actuator/prometheus
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
                  action: keep
                  regex: backend
                - source_labels: [__meta_kubernetes_pod_container_port_name]
                  action: keep
                  regex: management
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: pod
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
