apiVersion: 1
prune: true

datasources:
- name: VictoriaMetrics
  type: prometheus
  access: proxy
  orgId: 1
  uid: victoriametrics
  url: http://victoriametrics:8428
  basicAuth: false
  basicAuthUser: ""
  withCredentials: false
  isDefault: true
  editable: false
  jsonData:
    httpMethod: POST
    queryTimeout: 10s
    timeInterval": 10s
